[package]
name = "pacc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
indexmap = { version = "2.11.3", features = ["serde"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_yaml = "0.9.34"
